name: Python Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 'Create env file'
      run: |
        touch .env
        echo KEY=${{ secrets.KEY }} >> .env
        cat .env
    - name: Test with unittest
      run: |
        python -m unittest unit.py

  Deploy:
    needs: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRET_HOST }}
          username: ${{ secrets.SECRET_USER }}
          key: ${{ secrets.SECRET_KEY }}
          port: 22
          script: |
            cd app/python
            git pull